language: csharp
mono: none
dotnet: 2.1.400

sudo: required

git:
  depth: false

script:
  - dotnet restore dotnet-packaging.sln
  - dotnet pack dotnet-packaging.sln -c Release
  - dotnet test Packaging.Targets.Tests/Packaging.Targets.Tests.csproj

  - cd $TRAVIS_BUILD_DIR/demo/aspnetcore
  - dotnet restore
  - dotnet rpm -c Release -r rhel.7-x64 -f netcoreapp2.0
  - dotnet deb -c Release -r ubuntu.16.04-x64 -f netcoreapp2.0

  - cd $TRAVIS_BUILD_DIR/demo/cliscd/
  - dotnet restore

  - ./run-tests.sh -r centos.7-x64
  - ./run-tests.sh -r ol.7-x64

  - ./run-tests.sh -r fedora.27-x64
  - ./run-tests.sh -r fedora.28-x64

  - ./run-tests.sh -r debian.8-x64
  - ./run-tests.sh -r debian.9-x64

  - ./run-tests.sh -r ubuntu.14.04-x64
  - ./run-tests.sh -r ubuntu.16.04-x64
  - ./run-tests.sh -r ubuntu.18.04-x64

  - ./run-tests.sh -r opensuse.42.3-x64
