language: csharp
mono: none
dotnet: 2.1.400

env:
  - RUNTIME=centos.7-x64
  - RUNTIME=ol.7-x64
  - RUNTIME=fedora.27-x64
  - RUNTIME=fedora.28-x64
  - RUNTIME=debian.8-x64
  - RUNTIME=debian.9-x64
  - RUNTIME=ubuntu.14.04-x64
  - RUNTIME=ubuntu.16.04-x64
  - RUNTIME=ubuntu.18.04-x64
  - RUNTIME=opensuse.42.3-x64

sudo: required

git:
  depth: false

script:
  - dotnet restore dotnet-packaging.sln
  - dotnet pack dotnet-packaging.sln -c Release
  - dotnet test Packaging.Targets.Tests/Packaging.Targets.Tests.csproj

  - cd $TRAVIS_BUILD_DIR/demo/aspnetcore
  - dotnet restore
  - if [ "$RUNTIME" = "rhel.7-x64" ]; then dotnet rpm -c Release -r rhel.7-x64 -f netcoreapp2.1; fi
  - if [ "$RUNTIME" = "ubuntu.16.04-x64" ]; then dotnet deb -c Release -r ubuntu.16.04-x64 -f netcoreapp2.1; fi

  - cd $TRAVIS_BUILD_DIR/demo/cliscd/
  - dotnet restore

  - ./run-tests.sh -r $RUNTIME