language: csharp
mono: none
dotnet: 2.1.400

git:
  depth: false

script:
  - dotnet restore dotnet-packaging.sln
  - dotnet pack dotnet-packaging.sln -c Release
  - dotnet test Packaging.Targets.Tests/Packaging.Targets.Tests.csproj

  - cd $TRAVIS_BUILD_DIR/demo/aspnetcore
  - dotnet restore
  - dotnet rpm -c Release -r rhel.7-x64 -f netcoreapp2.0
  - dotnet deb -c Release -r ubuntu.16.04-x64 -f netcoreapp2.0

  - cd $TRAVIS_BUILD_DIR/demo/cliscd/
  - dotnet restore

  - dotnet deb -c Release -r debian.8-x64 -f netcoreapp2.1
  - cp bin/Release/netcoreapp2.1/debian.8-x64/cliscd.1.0.0.debian.8-x64.deb debian.8-x64/
  - sudo docker build -t clisc:debian.8-x64 debian.8-x64
  - sudo docker run clisc:debian.8-x64

  - dotnet deb -c Release -r ubuntu.18.04-x64 -f netcoreapp2.1
  - cp bin/Release/netcoreapp2.1/ubuntu.18.04-x64/cliscd.1.0.0.ubuntu.18.04-x64.deb ubuntu.18.04-x64/
  - sudo docker build -t clisc:ubuntu.18.04-x64 ubuntu.18.04-x64
  - sudo docker run clisc:ubuntu.18.04-x64

  - dotnet deb -c Release -r ubuntu.16.04-x64 -f netcoreapp2.1
  - cp bin/Release/netcoreapp2.1/ubuntu.16.04-x64/cliscd.1.0.0.ubuntu.16.04-x64.deb ubuntu.16.04-x64/
  - sudo docker build -t clisc:ubuntu.16.04-x64 ubuntu.16.04-x64
  - sudo docker run clisc:ubuntu.16.04-x64

  - dotnet rpm -c Release -r opensuse-x64 -f netcoreapp2.1
  - dotnet rpm -c Release -r ol-x64 -f netcoreapp2.1
  - dotnet rpm -c Release -r rhel-x64 -f netcoreapp2.1
  - dotnet rpm -c Release -r fedora-x64 -f netcoreapp2.1

  - dotnet rpm -c Release -r centos.7-x64 -f netcoreapp2.1
  - cp bin/Release/netcoreapp2.1/centos.7-x64/cliscd.1.0.0.centos.7-x64.rpm centos.7-x64
  - sudo docker build -t clisc:centos.7-x64 centos.7-x64
#  - sudo docker run clisc:centos.7-x64
