language: csharp
mono: none
dotnet: 2.1.400

git:
  depth: false

script:
  - dotnet restore dotnet-packaging.sln
  - dotnet pack dotnet-packaging.sln -c Release
  - dotnet test Packaging.Targets.Tests/Packaging.Targets.Tests.csproj

  - cd demo/aspnetcore
  - dotnet restore
  - dotnet rpm -c Release -r rhel.7-x64 -f netcoreapp2.0
  - dotnet deb -c Release -r ubuntu.16.04-x64 -f netcoreapp2.0
