image: Visual Studio 2017

version: '0.1.{build}'
skip_branch_with_pr: true

before_build:
  - dotnet restore dotnet-packaging.sln

build_script:
  - dotnet pack dotnet-packaging.sln -c Release

test_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%\Packaging.Targets.Tests\
  - cmd: dotnet restore
  - cmd: dotnet build
  - cmd: dotnet vstest bin\Debug\netcoreapp2.0\Packaging.Targets.Tests.dll /logger:trx;LogFileName=testresults.trx
  - ps: '& (Join-Path $env:APPVEYOR_BUILD_FOLDER "appveyor-testresults.ps1")'
  - cmd: cd ..

  - cmd: cd %APPVEYOR_BUILD_FOLDER%/demo/aspnetcore
  - cmd: dotnet restore
  - cmd: dotnet rpm -c Release -r rhel.7-x64 -f netcoreapp2.0
  - cmd: dotnet deb -c Release -r ubuntu.16.04-x64 -f netcoreapp2.0

  - cmd: cd %APPVEYOR_BUILD_FOLDER%/demo/cliscd/
  - cmd: dotnet restore

  # Test on Debian 8
  - cmd: dotnet deb -c Release -r debian.8-x64 -f netcoreapp2.1
  - cmd: copy bin\Release\netcoreapp2.1\debian.8-x64\cliscd.1.0.0.debian.8-x64.deb debian.8-x64\
#  - cmd: docker build -t clisc:debian.8-x64 debian.8-x64
#  - cmd: docker run clisc:debian.8-x64

  - cmd: dotnet deb -c Release -r ubuntu.18.04-x64 -f netcoreapp2.1
  - cmd: dotnet deb -c Release -r ubuntu.16.04-x64 -f netcoreapp2.1
  - cmd: dotnet rpm -c Release -r opensuse.42.3-x64 -f netcoreapp2.1
  - cmd: dotnet rpm -c Release -r ol.7-x64 -f netcoreapp2.1
  - cmd: dotnet rpm -c Release -r rhel-x64 -f netcoreapp2.1
  - cmd: dotnet rpm -c Release -r fedora.28-x64 -f netcoreapp2.1

  # Test on CentOS 7
  - cmd: dotnet rpm -c Release -r centos.7-x64 -f netcoreapp2.1
  - cmd: copy bin\Release\netcoreapp2.1\centos.7-x64\cliscd.1.0.0.centos.7-x64.deb centos.7-x64\
#  - cmd: docker build -t clisc:centos.7-x64 centos.7-x64
#  - cmd: docker run clisc:centos.7-x64

artifacts:
  - path: dotnet-tarball\bin\Release\dotnet-tarball.*.nupkg
  - path: dotnet-zip\bin\Release\dotnet-zip.*.nupkg
  - path: dotnet-rpm\bin\Release\dotnet-rpm.*.nupkg
  - path: dotnet-deb\bin\Release\dotnet-deb.*.nupkg
  - path: Packaging.Targets\bin\Release\Packaging.Targets.*.nupkg
  - path: demo\**\*.deb
  - path: demo\**\*.rpm

deploy:
  provider: NuGet
  on:
    branch: master
  api_key:
    secure: PWTSvjALUGYuMrcnQX7RZxDW/M8WtIXfihQUek4xMjN2bQj73gudiusqIOVUEwdo
  skip_symbols: true
